# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vm.provider :virtualbox do |vb|
      config.vbguest.auto_update = false
    end
  end
  
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.vmx["memsize"] = "2048"
    vmware.vmx["numvcpus"] = "1"
  end
    

  config.vm.define "server" do |server|
    server.vm.box = "centos/7"

    server.vm.provider "virtualbox" do |vb|
      vb.name =  "project.server.local"
      vb.memory = 2048
      vb.cpus = 1
    end
  
    server.vm.network "private_network", ip: "192.168.50.4"
    server.vm.synced_folder "../userapi", "/home/app", type: "virtualbox", nfs: false

    server.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbooks/run.yml"
      ansible.tags = ["install", "check"]
    end
  end
end

