version: "3"
services:
  redis:
    image: redis
  app:
    depends_on:
      - redis
    image: inchirahj/devops-project
    ports:
      - "6500:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379