---
- name: Install redis
  yum:
    name: redis
    state: latest

- name: Enable and start redis
  service:
    name: redis
    state: started
    enabled: yes

- name: Install node and npm
  yum:
    name: npm
    state: present

- name: Install app dependencies
  npm:
    path: "/home/app"
